import { existsSync } from "node:fs";
import { copyFile, mkdir, readdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { isMainModule, refuseTestWorker } from "../cli/is-main.ts";
import { loadSyncConfig } from "../sync/config.ts";
import { runGit } from "./git.ts";

/**
 * data:init — seed the data repo named by `sync.json`'s `dataRoot`
 * (issue #29). The code repo versions only the directory skeleton; the
 * contents of `raw/` and `wiki/` live in, and are versioned by, the data
 * repo. Seeding copies the skeleton (`git ls-files`, so the copy cannot
 * drift from what the code repo versions), writes a README, and makes
 * the initial commit. Idempotent: a seeded data root is left untouched.
 */

export interface SeedOptions {
  /** Path to `sync.json`. */
  readonly configPath: string;
  /** Code repo root; defaults to this module's repository. */
  readonly repoRoot?: string;
  /** Environment for git child processes; defaults to `process.env`. */
  readonly env?: NodeJS.ProcessEnv;
  /** Write the operator-owned second-brain identity marker
   *  (issue #94) at the data root and commit it with the skeleton. */
  readonly secondBrain?: boolean;
  /** Seed the meta contract (issue #74) as the data repo's
   *  wiki/AGENTS.md instead of the canonical wiki contract. */
  readonly meta?: boolean;
}

const DATA_README = `# k-wiki data

Derived data for the k-wiki pipeline:

- \`raw/\` — immutable projection of selected source notes;
- \`raw/manifest.json\` — sync state;
- \`wiki/\` — the LLM-maintained knowledge base.

Generated by the k-wiki code repo (see its guide, Sections 19 and 26).
Do not edit by hand — the pipeline writes here. This repository can hold
personal material: push it only to a private remote you control.
`;

/** The data root counts as seeded once the wiki skeleton is present. */
function isSeeded(dataRoot: string): boolean {
  return existsSync(join(dataRoot, "wiki", "index.md"));
}

/** The canonical meta contract (issue #74): copied into a meta data
 *  repo as its wiki/AGENTS.md, never shipped as itself. */
const META_CONTRACT = "wiki/AGENTS.meta.md";

/** List the skeleton paths the code repo versions under raw/ and wiki/,
 *  minus the meta contract template. */
async function listSkeletonPaths(
  repoRoot: string,
  env: NodeJS.ProcessEnv,
): Promise<readonly string[]> {
  const { stdout } = await runGit(
    repoRoot,
    ["ls-files", "--", "raw", "wiki"],
    env,
  );

  return stdout
    .split("\n")
    .filter(Boolean)
    .filter((relPath) => relPath !== META_CONTRACT)
    .sort();
}

/** Copy the skeleton and commit it as the data repo's first commit. */
async function seed(
  dataRoot: string,
  repoRoot: string,
  env: NodeJS.ProcessEnv,
  secondBrain: boolean,
  meta: boolean,
): Promise<void> {
  await mkdir(dataRoot, { recursive: true });
  await runGit(dataRoot, ["init", "--quiet"], env);

  for (const relPath of await listSkeletonPaths(repoRoot, env)) {
    const destination = join(dataRoot, relPath);

    await mkdir(dirname(destination), { recursive: true });
    await copyFile(join(repoRoot, relPath), destination);
  }

  await writeFile(join(dataRoot, "README.md"), DATA_README);

  if (secondBrain) {
    await writeFile(join(dataRoot, ".second-brain"), "");
  }

  if (meta) {
    await copyFile(
      join(repoRoot, META_CONTRACT),
      join(dataRoot, "wiki", "AGENTS.md"),
    );
  }

  const message = "Seed data repo from k-wiki skeleton";

  await runGit(dataRoot, ["add", "-A"], env);
  await runGit(dataRoot, ["commit", "--quiet", "-m", message], env);
}

/** Seed the data repo at the configured `dataRoot`. */
export async function seedDataRepo(
  options: SeedOptions,
): Promise<"seeded" | "already-seeded"> {
  const repoRoot = options.repoRoot ?? defaultRepoRoot;
  const env = options.env ?? process.env;
  const config = await loadSyncConfig(options.configPath);

  if (config.dataRoot === undefined) {
    throw new Error(`no "dataRoot" in ${options.configPath}: nothing to seed`);
  }

  if (isSeeded(config.dataRoot)) {
    return "already-seeded";
  }

  if (existsSync(config.dataRoot)) {
    const entries = await readdir(config.dataRoot);

    if (entries.length > 0) {
      throw new Error(
        `${config.dataRoot} is not empty and is not a seeded data repo; ` +
          'refusing to seed into it — move its contents or point "dataRoot" ' +
          "at an empty directory",
      );
    }
  }

  await seed(
    config.dataRoot,
    repoRoot,
    env,
    options.secondBrain === true,
    options.meta === true,
  );

  return "seeded";
}

const defaultRepoRoot = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../..",
);

/** Help text: every switch, argument, and default (AGENTS.md CLI rule). */
const HELP = `Usage: init-data-repo [-h | --help] [--second-brain] [--meta] [<config>]

Create and seed the data repo at the config's dataRoot: git init, copy
the raw/ and wiki/ skeleton from the code repo, first commit.
Idempotent — an already-seeded data repo is left untouched.

  --second-brain  Also write .second-brain, the operator-owned
                  second-brain identity marker, at the data root and
                  commit it with the seed. The marker — not the
                  agent-writable wiki/second-brain/profile.md — is
                  what the ingest guardrails read as second-brain
                  identity (issue #94). Mark an already-seeded repo
                  by hand: create and commit .second-brain at its
                  root.
  --meta          Seed the meta contract (issue #74) as the data
                  repo's wiki/AGENTS.md instead of the canonical
                  wiki contract: the repo-as-source wiki that
                  documents k-wiki itself, describe-don't-prescribe.
  -h, --help      Print this help and exit; no side effects.
  <config>        Path to sync.json.
                  Default: the repo's own sync.json.`;

/** data:init entry point: `init-data-repo [-h | --help] [--second-brain] [<config>]`. */
export async function main(): Promise<void> {
  refuseTestWorker("data:init");

  const args = process.argv.slice(2);

  if (args.includes("-h") || args.includes("--help")) {
    console.log(HELP);

    return;
  }

  const secondBrain = args.includes("--second-brain");
  const meta = args.includes("--meta");
  const configArg = args.find(
    (arg) => arg !== "--second-brain" && arg !== "--meta",
  );
  const configPath = configArg ?? join(defaultRepoRoot, "sync.json");

  try {
    const config = await loadSyncConfig(configPath);
    const result = await seedDataRepo({ configPath, secondBrain, meta });

    console.log(
      result === "seeded"
        ? `data:init: seeded ${config.dataRoot}`
        : `data:init: ${config.dataRoot} already seeded`,
    );
  } catch (error) {
    console.error(
      `data:init: ${error instanceof Error ? error.message : String(error)}`,
    );

    process.exitCode = 1;
  }
}

const isMain = isMainModule(import.meta.url);

/* v8 ignore next: covered only under `node src/data/init-data-repo.ts` */
if (isMain) {
  await main();
}
