import { execFile } from "node:child_process";
import { existsSync } from "node:fs";
import { copyFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { promisify } from "node:util";
import { loadSyncConfig } from "../sync/config.ts";

const run = promisify(execFile);

/**
 * data:init — seed the data repo named by `sync.json`'s `dataRoot`
 * (issue #29). The code repo versions only the directory skeleton; the
 * contents of `raw/` and `wiki/` live in, and are versioned by, the data
 * repo. Seeding copies the skeleton (`git ls-files`, so the copy cannot
 * drift from what the code repo versions), writes a README, and makes
 * the initial commit. Idempotent: a seeded data root is left untouched.
 */

export interface SeedOptions {
  /** Path to `sync.json`. */
  readonly configPath: string;
  /** Code repo root; defaults to this module's repository. */
  readonly repoRoot?: string;
  /** Environment for git child processes; defaults to `process.env`. */
  readonly env?: NodeJS.ProcessEnv;
}

const DATA_README = `# k-wiki data

Derived data for the k-wiki pipeline:

- \`raw/\` — immutable projection of selected source notes;
- \`raw/manifest.json\` — sync state;
- \`wiki/\` — the LLM-maintained knowledge base.

Generated by the k-wiki code repo (see its guide, Sections 19 and 26).
Do not edit by hand — the pipeline writes here. This repository can hold
personal material: push it only to a private remote you control.
`;

/** The data root counts as seeded once the wiki skeleton is present. */
function isSeeded(dataRoot: string): boolean {
  return existsSync(join(dataRoot, "wiki", "index.md"));
}

/** List the skeleton paths the code repo versions under raw/ and wiki/. */
async function listSkeletonPaths(
  repoRoot: string,
  env: NodeJS.ProcessEnv,
): Promise<readonly string[]> {
  const { stdout } = await run(
    "git",
    ["-C", repoRoot, "ls-files", "--", "raw", "wiki"],
    { env },
  );

  return stdout.split("\n").filter(Boolean).sort();
}

/** Copy the skeleton and commit it as the data repo's first commit. */
async function seed(
  dataRoot: string,
  repoRoot: string,
  env: NodeJS.ProcessEnv,
): Promise<void> {
  await mkdir(dataRoot, { recursive: true });
  await run("git", ["-C", dataRoot, "init", "--quiet"], { env });

  for (const relPath of await listSkeletonPaths(repoRoot, env)) {
    const destination = join(dataRoot, relPath);

    await mkdir(dirname(destination), { recursive: true });
    await copyFile(join(repoRoot, relPath), destination);
  }

  await writeFile(join(dataRoot, "README.md"), DATA_README);

  const message = "Seed data repo from k-wiki skeleton";

  await run("git", ["-C", dataRoot, "add", "-A"], { env });
  await run("git", ["-C", dataRoot, "commit", "--quiet", "-m", message], {
    env,
  });
}

/** Seed the data repo at the configured `dataRoot`. */
export async function seedDataRepo(
  options: SeedOptions,
): Promise<"seeded" | "already-seeded"> {
  const repoRoot = options.repoRoot ?? defaultRepoRoot;
  const env = options.env ?? process.env;
  const config = await loadSyncConfig(options.configPath);

  if (config.dataRoot === undefined) {
    throw new Error(`no "dataRoot" in ${options.configPath}: nothing to seed`);
  }

  if (isSeeded(config.dataRoot)) {
    return "already-seeded";
  }

  await seed(config.dataRoot, repoRoot, env);

  return "seeded";
}

const defaultRepoRoot = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../..",
);

/** data:init entry point: `init-data-repo [config]`. */
export async function main(): Promise<void> {
  const [configArg] = process.argv.slice(2);
  const configPath = configArg ?? join(defaultRepoRoot, "sync.json");

  try {
    const config = await loadSyncConfig(configPath);
    const result = await seedDataRepo({ configPath });

    console.log(
      result === "seeded"
        ? `data:init: seeded ${config.dataRoot}`
        : `data:init: ${config.dataRoot} already seeded`,
    );
  } catch (error) {
    console.error(
      `data:init: ${error instanceof Error ? error.message : String(error)}`,
    );

    process.exitCode = 1;
  }
}

/* v8 ignore next: import guard — distinguishes direct execution from
   import; not exercisable in-process by construction */
const isMain =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href;

/* v8 ignore next: covered only under `node src/data/init-data-repo.ts` */
if (isMain) {
  await main();
}
