import { existsSync } from "node:fs";
import {
  copyFile,
  mkdir,
  readdir,
  readFile,
  writeFile,
} from "node:fs/promises";
import { dirname, join } from "node:path";
import { repoRoot } from "../cli/shared.ts";
import { runGit } from "./git.ts";

/**
 * data:init — seed the data repo at a given `dataRoot` (issue #29).
 * The code repo versions only the directory skeleton; the contents
 * of `raw/` and `wiki/` live in, and are versioned by, the data repo.
 * Seeding copies the skeleton (`git ls-files`, so the copy cannot
 * drift from what the code repo versions), writes a README, and makes
 * the initial commit. Idempotent: a seeded data root is left untouched.
 * The sync.json read lives in the cli shell (RC1 split): this module
 * is a pure library with no config access.
 */

export interface SeedOptions {
  /** Data repo root to seed. */
  readonly dataRoot: string;
  /** Code repo root; defaults to this module's repository. */
  readonly repoRoot?: string;
  /** Environment for git child processes; defaults to `process.env`. */
  readonly env?: NodeJS.ProcessEnv;
  /** Write the operator-owned second-brain identity marker
   *  (issue #94) at the data root and commit it with the skeleton. */
  readonly secondBrain?: boolean;
  /** Seed the meta contract (issue #74) as the data repo's
   *  wiki/AGENTS.md instead of the canonical wiki contract. */
  readonly meta?: boolean;
}

const DATA_README = `# k-wiki data

Derived data for the k-wiki pipeline:

- \`raw/\` — immutable projection of selected source notes;
- \`raw/manifest.json\` — sync state;
- \`wiki/\` — the LLM-maintained knowledge base.

Generated by the k-wiki code repo (see its guide, Sections 19 and 26).
Do not edit by hand — the pipeline writes here. This repository can hold
personal material: push it only to a private remote you control.
`;

/** The data root counts as seeded only when both halves of a
 *  completed seed are present: the skeleton marker (wiki/index.md) and
 *  a resolvable HEAD — the commit is seed()'s final step. Either half
 *  alone — a partially copied skeleton (an interrupted run), or an
 *  unrelated committed repo at a wrong dataRoot — falls through to the
 *  non-empty-directory refusal (issue #246 C-8). */
async function isSeeded(
  dataRoot: string,
  env: NodeJS.ProcessEnv,
): Promise<boolean> {
  if (!existsSync(join(dataRoot, "wiki", "index.md"))) {
    return false;
  }

  try {
    await runGit(dataRoot, ["rev-parse", "--verify", "HEAD"], env);

    return true;
  } catch {
    return false;
  }
}

/** The canonical meta contract (issue #74): copied into a meta data
 *  repo as its wiki/AGENTS.md, never shipped as itself. */
const META_CONTRACT = "wiki/AGENTS.meta.md";

/** List the skeleton paths the code repo versions under raw/ and wiki/,
 *  minus the meta contract template. */
async function listSkeletonPaths(
  repoRoot: string,
  env: NodeJS.ProcessEnv,
): Promise<readonly string[]> {
  const { stdout } = await runGit(
    repoRoot,
    ["ls-files", "--", "raw", "wiki"],
    env,
  );

  return stdout
    .split("\n")
    .filter(Boolean)
    .filter((relPath) => relPath !== META_CONTRACT)
    .sort();
}

/** The standing .gitignore rules every data repo must carry (issue
 *  #146): the ones both live data repos converged on by hand after
 *  incidents — Obsidian UI state (an open Obsidian writing into the
 *  repo trips guardrail 1, so the rule must predate the files) and
 *  the wiki-ingest snapshot (per-instance state, issue #112).
 *  gitignore does not apply to already-tracked files; wiki-ingest
 *  warns pre-flight when that happens. */
const STANDING_IGNORE_BLOCKS = [
  {
    comment:
      "# Obsidian UI state: never part of the wiki (external writer; guardrail 1 hazard)",
    entries: [".obsidian/", "wiki/.obsidian/"],
  },
  {
    comment:
      "# wiki-ingest manifest snapshot: per-instance state, never committed (issue #112)",
    entries: ["outputs/last-ingested-manifest.json"],
  },
] as const;

/** Write the standing ignore rules into the data repo's .gitignore,
 *  merging any missing entries into an existing file — idempotent:
 *  a .gitignore that already carries every rule is left untouched. */
export async function seedStandingIgnores(dataRoot: string): Promise<void> {
  const ignorePath = join(dataRoot, ".gitignore");
  const existing = await readFile(ignorePath, "utf8").catch(() => "");
  const present = new Set(existing.split("\n").map((line) => line.trim()));
  const additions: string[] = [];

  for (const block of STANDING_IGNORE_BLOCKS) {
    const missing = block.entries.filter((entry) => !present.has(entry));

    if (missing.length > 0) {
      additions.push(block.comment, ...missing);
    }
  }

  if (additions.length === 0) {
    return;
  }

  const body =
    existing === "" || existing.endsWith("\n") ? existing : `${existing}\n`;

  await writeFile(ignorePath, `${body}${additions.join("\n")}\n`, "utf8");
}

/** Copy the skeleton and commit it as the data repo's first commit. */
async function seed(options: {
  readonly dataRoot: string;
  readonly repoRoot: string;
  readonly env: NodeJS.ProcessEnv;
  readonly secondBrain: boolean;
  readonly meta: boolean;
}): Promise<void> {
  const { dataRoot, repoRoot, env } = options;
  await mkdir(dataRoot, { recursive: true });
  await runGit(dataRoot, ["init", "--quiet"], env);

  for (const relPath of await listSkeletonPaths(repoRoot, env)) {
    const destination = join(dataRoot, relPath);

    await mkdir(dirname(destination), { recursive: true });
    await copyFile(join(repoRoot, relPath), destination);
  }

  await writeFile(join(dataRoot, "README.md"), DATA_README);

  if (options.secondBrain) {
    await writeFile(join(dataRoot, ".second-brain"), "");
  }

  if (options.meta) {
    await copyFile(
      join(repoRoot, META_CONTRACT),
      join(dataRoot, "wiki", "AGENTS.md"),
    );
  }

  await seedStandingIgnores(dataRoot);

  const message = "Seed data repo from k-wiki skeleton";

  await runGit(dataRoot, ["add", "-A"], env);
  await runGit(dataRoot, ["commit", "--quiet", "-m", message], env);
}

/** Seed the data repo at the given `dataRoot`. */
export async function seedDataRepo(
  options: SeedOptions,
): Promise<"seeded" | "already-seeded"> {
  const root = options.repoRoot ?? repoRoot;
  const env = options.env ?? process.env;
  const dataRoot = options.dataRoot;

  if (await isSeeded(dataRoot, env)) {
    return "already-seeded";
  }

  if (existsSync(dataRoot)) {
    const entries = await readdir(dataRoot);

    if (entries.length > 0) {
      throw new Error(
        `${dataRoot} is not empty and is not a seeded data repo; ` +
          'refusing to seed into it — move its contents or point "dataRoot" ' +
          "at an empty directory",
      );
    }
  }

  await seed({
    dataRoot,
    repoRoot: root,
    env,
    secondBrain: options.secondBrain === true,
    meta: options.meta === true,
  });

  return "seeded";
}
